### ISSUE TITLE
Multiple highlighter not working

### ISSUE THREAD

**Issue by yashjain2890** [sdar/Multiple-Highlighter#4] opened 2016-05-05 12:44 UTC
It isn't working and there is no option to add keywords and highlight multiple keywords. It is not as shown on the display
![bug](https://cloud.githubusercontent.com/assets/11141643/15045879/40646064-12dd-11e6-9a39-d0c3e318438c.png)

**Comment by sdar** [comment] 2016-05-05 12:55
Hi, and thank you for reporting a possible bug, I'm currently testing the addon on stable, developer, aurora and nightly and seems to work as expected, can you provide the following info?

-Os version.
-Browser name/version.
-Installed addons
-Preferences modified (maybe local storage disabled?)

Thank you.

![capture](https://cloud.githubusercontent.com/assets/11141643/15043996/d6253882-12d1-11e6-98d8-4f9bc59d2204.PNG)

**Comment by yashjain2890** [comment] 2016-05-05 13:08
-Os version – Windows 07 – 64 Bit
-Browser name/version – Mozila Firefox
-Installed addons – Multiple Highlighter/ https://addons.mozilla.org/en-US/firefox/addon/multiple-highlighter/?src=search
-Preferences modified (maybe local storage disabled?) -  I do not really understand what this would mean.

**Comment by sdar** [comment] 2016-05-05 14:18
Can you confirm it's the latest version (46.0.x) as shown in the image:
![capture](https://cloud.githubusercontent.com/assets/11141643/15045684/3d6feea6-12dc-11e6-8d9e-61e7796bf6cb.PNG)

I'm having lots of problems trying to reproduce the bug here, the addon seems to work no matter what i do, and it's almost exclusively using high level sdk apis so it should be hard for it to fail.

~~Can you try installing it on a clean profile? maybe something is wrong with it.~~

**Comment by sdar** [comment] 2016-05-05 14:54
I'm quite sure I've found the problem, I've tested the addon in an outdated version of firefox (38.x) and it looks exactly like your image, that's caused by the use of features that were introduced recently on the ecmascript 6 standard, so the addon only works with firefox 44 or newer versions (current stable is 46 and the esr is 45).

So hopefully updating your browser will fix the problem, I'll wait your response before closing the bug.

**Comment by sdar** [comment] 2016-05-20 14:55
Well, i suppose that the version should be the problem, feel free to re-open or fill another bug if i'm wrong, I'll close this one as I've no response since 15 days ago.

**Closed as completed** 2016-05-20 14:55 UTC
